# Generated by Django 4.0.3 on 2024-02-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pellets',
            fields=[
                ('item_number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('unit_price', models.PositiveSmallIntegerField()),
                ('stock', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
